FROM nginx
MAINTAINER xtam
VOLUME /tmp
ENV LANG en_US.UTF-8
COPY ./ /usr/share/nginx/html/
# 生产环境不支持代理, 使用 nginx 代理
RUN echo "server {  \
                  location   /jeecgboot { \
                      proxy_pass              http://192.168.2.17:8080/jeecg-boot; \
                      proxy_set_header        X-Real-IP \$remote_addr; \
                      proxy_set_header        X-Forwarded-For \$proxy_add_x_forwarded_for; \
                  } \
                  #解决Router(mode: 'history')模式下，刷新路由地址不能找到页面的问题 \
                    # https://juejin.cn/post/7134100358644629535 \
                    location / { \
                        root /usr/share/nginx/html; \
                        index index.html; \
                        try_files \$uri \$uri/ /index.html; \
                    } \
                  access_log  /var/log/nginx/access.log ; \
              } " > /etc/nginx/conf.d/default.conf \
    &&  mkdir  -p  /usr/share/nginx/html
EXPOSE 80
EXPOSE 443